// <auto-generated />
using System;
using AzureServiceBus.Employee.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AzureServiceBus.Employee.Infrastructure.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20201126054837_PrimaryKeyChanges")]
    partial class PrimaryKeyChanges
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AzureServiceBus.Employee.Infrastructure.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("68bf1cbd-68b6-43cd-b810-f8814aaf8a3f"),
                            Address = "",
                            Contact = "",
                            CreatedBy = "",
                            CreatedOn = new DateTime(2020, 11, 26, 11, 18, 37, 536, DateTimeKind.Local).AddTicks(6028),
                            DepartmentName = "Dot Net",
                            EmpCode = "63550340-c2fb-4ff4-964a-601df8d3a54f",
                            FirstName = "Sandeep",
                            IsActive = true,
                            JoiningDate = new DateTime(2020, 11, 26, 11, 18, 37, 535, DateTimeKind.Local).AddTicks(5729),
                            LastName = "Kumar",
                            ModifiedBy = "",
                            ModifiedOn = new DateTime(2020, 11, 26, 11, 18, 37, 536, DateTimeKind.Local).AddTicks(6851)
                        },
                        new
                        {
                            Id = new Guid("02b71caf-7d25-45bc-9876-d031065e38c9"),
                            Address = "",
                            Contact = "",
                            CreatedBy = "",
                            CreatedOn = new DateTime(2020, 11, 26, 11, 18, 37, 536, DateTimeKind.Local).AddTicks(7389),
                            DepartmentName = "QA",
                            EmpCode = "a1b50ce0-954f-423a-b1a2-48f2872ec8c8",
                            FirstName = "Praveen",
                            IsActive = true,
                            JoiningDate = new DateTime(2020, 11, 26, 11, 18, 37, 536, DateTimeKind.Local).AddTicks(7345),
                            LastName = "Kumar",
                            ModifiedBy = "",
                            ModifiedOn = new DateTime(2020, 11, 26, 11, 18, 37, 536, DateTimeKind.Local).AddTicks(7407)
                        },
                        new
                        {
                            Id = new Guid("a230239e-4709-49e1-a3e5-54c8d8ea0ce4"),
                            Address = "",
                            Contact = "",
                            CreatedBy = "",
                            CreatedOn = new DateTime(2020, 11, 26, 11, 18, 37, 536, DateTimeKind.Local).AddTicks(7420),
                            DepartmentName = "Sales",
                            EmpCode = "139fc502-9189-4ffc-9e54-106e6b23d1a0",
                            FirstName = "Mukul",
                            IsActive = true,
                            JoiningDate = new DateTime(2020, 11, 26, 11, 18, 37, 536, DateTimeKind.Local).AddTicks(7415),
                            LastName = "Bansal",
                            ModifiedBy = "",
                            ModifiedOn = new DateTime(2020, 11, 26, 11, 18, 37, 536, DateTimeKind.Local).AddTicks(7421)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
